version: '3'
services:
    resume:
        image: slzcc/resumecrm:v4
        container_name: resume_server
        ports:
          - 8088:8088
        environment:
            MYSQL_DATABASE: resume
            MYSQL_USER: resume
            MYSQL_PASSWORD: resume
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: example.org
            MYSQL_HOST: mysql
            MYSQL_PORT: 3306
            SOLR_SERVER_URL: "http://solr:8983/"
            NGINX_MIRROR_ADDRESS: "http://upload_frontend"
            TRANSCODE_PDF_ADDRESS: "http://transcode:8089/api/v1/file/pdf"
        hostname: "resumecrm.shileizcc.com"
        depends_on:
           - mysql
           - solr
           - results
           - broker
        networks:
           - resume

    transcode:
        image: slzcc/django:transcode-pdf-uwsgi-v5
        container_name: resume_transcode
        ports:
          - 8089:8089
        environment:
            MYSQL_DATABASE: resumec
            MYSQL_USER: resumec
            MYSQL_PASSWORD: resumec
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: example.org
            MYSQL_HOST: mysql
            MYSQL_PORT: 3306
            NGINX_MIRROR_ADDRESS: "http://upload_frontend/"
            TZ: Asia/Shanghai
        depends_on:
           - mysql
        networks:
           - resume

    mysql:
        image: slzcc/mysql:5.6-custom
        environment:
            MYSQL_ROOT_PASSWORD: example.org
            MYSQL_DATABASE: resume
            MYSQL_USER: resume
            MYSQL_PASSWORD: resume
            TZ: Asia/Shanghai
        container_name: resume_mysql
        volumes:
          - mysql:/var/lib/mysql
        networks:
           - resume

    upload_backend:
        image: slzcc/django:upload-uwsgi-v5
        container_name: resume_upload_backend
        ports:
          - 8878:8878
        environment:
            TZ: Asia/Shanghai
            UPLOAD_FILE_PATH: "/storage/"
            NGINX_MIRROR_URL: "http://upload_frontend/"
            NGINX_MIRROR_STORAGE_PATH: "firmware/resume"
            REMOVE_SOURCE_FILE_SETUP: "False"
            USE_TIEM_SUB_DIRECTORY: "False"
        networks:
           - resume
        volumes:
          - nginx-upload:/tmp/nginx_upload
          - mirror:/storage
 
    upload_frontend:
        image: slzcc/nginx:upload-conf-v3
        container_name: resume_upload_frontend
        ports:
          - 80:80
        environment:
            TZ: Asia/Shanghai
            UPLOAD_BACKEND_ADDRESS: http://upload_backend:8878
            NGINX_MIRROR_HOME: /mirror
        volumes:
          - nginx-upload:/tmp/nginx_upload
          - mirror:/mirror
        networks:
           - resume
    solr:
        image: slzcc/solr:ik
        container_name: resume_solr
        ports:
          - 8983:8983
        environment:
            TZ: Asia/Shanghai
            MYSQL_HOST: 'mysql'
            MYSQL_PORT: 3306
            MYSQL_USERNAME: resume
            MYSQL_PASSWORD: resume
            MYSQL_DATABASE: resume
        volumes:
          - solr:/opt/solr/server/solr/gettingstarted/data
        depends_on:
           - mysql
        networks:
           - resume
    broker:
        container_name: resume_celery_broker
        image: rabbitmq
        environment:
            TZ: Asia/Shanghai
            RABBITMQ_DEFAULT_USER: resume
            RABBITMQ_DEFAULT_PASS: resume
            RABBITMQ_DEFAULT_VHOST: resume
        volumes:
          - broker:/var/lib/rabbitmq
        networks:
           - resume
    results:
        container_name: resume_celery_results
        image: redis
        environment:
            TZ: Asia/Shanghai
        volumes:
          - results:/data
        networks:
           - resume
           
volumes:
    nginx-upload:
    mirror:
    mysql:
    solr:
    broker:
    results:

networks:
  resume:
    driver: bridge