version: '3'
services:
    resume:
        image: slzcc/resumecrm:base
        container_name: resume_server
        ports:
          - 8088:8088
        environment:
            MYSQL_DATABASE: resume
            MYSQL_USER: resume
            MYSQL_PASSWORD: resume
            MYSQL_HOST: "mysql"
            MYSQL_PORT: 3306
            SOLR_SERVER_URL: "http://solr:8983/"
        volumes:
          - /Users/shilei/Documents/PyCharm/Django/ResumeCRM:/ResumeCRM
        hostname: "resumecrm.shileizcc.com"
        command: "sleep 1234567890"

    transcode:
        image: slzcc/django:transcode-pdf-uwsgi-v3
        container_name: resume_transcode
        ports:
          - 8089:8089
        environment:
            MYSQL_DATABASE: check_md5
            MYSQL_USER: check_md5
            MYSQL_PASSWORD: check_md5
            MYSQL_HOST: "mysql"
            MYSQL_PORT: 3306
            NGINX_MIRROR_ADDRESS: "http://10.30.0.41/"
            TZ: Asia/Shanghai
    mysql:
        image: slzcc/mysql:5.6-custom
        environment:
            MYSQL_ROOT_PASSWORD: example.org
            TZ: Asia/Shanghai
        container_name: resume_mysql
        volumes:
          - mysql:/var/lib/mysql

    upload_backend:
        image: slzcc/django:upload-uwsgi-v4
        container_name: resume_upload_backend
        ports:
          - 8878:8878
        environment:
            UPLOAD_FILE_PATH: "/storage/"
            NGINX_MIRROR_URL: "http://10.30.0.41/"
            NGINX_MIRROR_STORAGE_PATH: "firmware/resume"
            REMOVE_SOURCE_FILE_SETUP: "False"
            USE_TIEM_SUB_DIRECTORY: "False"
 
        volumes:
          - nginx-upload:/tmp/nginx_upload
          - mirror:/storage
 
    upload_frontend:
        image: slzcc/nginx:upload-conf-v3
        container_name: resume_upload_frontend
        ports:
          - 80:80
        environment:
            UPLOAD_BACKEND_ADDRESS: http://upload_backend:8878
            NGINX_MIRROR_HOME: /mirror
        volumes:
          - nginx-upload:/tmp/nginx_upload
          - mirror:/mirror
 
    solr:
        image: slzcc/solr:ik
        container_name: resume_solr
        ports:
          - 8983:8983
        environment:
            MYSQL_HOST: 'mysql'
            MYSQL_PORT: 3306
            MYSQL_USERNAME: resume
            MYSQL_PASSWORD: resume
            MYSQL_DATABASE: resume
        volumes:
          - solr:/opt/solr/server/solr/gettingstarted/data

    broker:
        container_name: resume_celery_broker
        image: rabbitmq
        environment:
          RABBITMQ_DEFAULT_USER: resume
          RABBITMQ_DEFAULT_PASS: resume
          RABBITMQ_DEFAULT_VHOST: resume
        volumes:
          - broker:/var/lib/rabbitmq

    results:
        container_name: resume_celery_results
        image: redis
        volumes:
          - results:/data
volumes:
    nginx-upload:
    mirror:
    mysql:
    solr:
    broker:
    results:
